name: Deploy Web

on:
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: make build-web
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./static
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
